CREATE OR REPLACE FUNCTION refresh_metrics_views()
RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_metrics_timeseries;
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_metrics_site;
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_metrics_dma;
END;
$$ LANGUAGE plpgsql;