CREATE OR REPLACE FUNCTION refresh_metrics_views()
RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_timeseries;
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_site;
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_dma;
END;
$$ LANGUAGE plpgsql;